//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KiewitTeamBinder.Api.MailServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.qa-software.com/", ConfigurationName="MailServiceReference.MailWebServiceSoap")]
    public interface MailWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListMail(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListMail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListMailAsync(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetMailDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailDetails(string sessionKey, string mailBox, int mailIntKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetMailDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailDetailsAsync(string sessionKey, string mailBox, int mailIntKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetAttachmentsDownloadLink", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAttachmentsDownloadLink(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetAttachmentsDownloadLink", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAttachmentsDownloadLinkAsync(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListNewMailTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListNewMailTypes(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListNewMailTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListNewMailTypesAsync(string sessionKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListReplyForwardMailTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListReplyForwardMailTypes(string sessionKey, string originatingMailType, string composeMailAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListReplyForwardMailTypes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListReplyForwardMailTypesAsync(string sessionKey, string originatingMailType, string composeMailAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetStructureForComposeMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetStructureForComposeMail(string sessionKey, int parentMailIntKey, string parentMailBox, string mailType, string composeMailAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetStructureForComposeMail", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetStructureForComposeMailAsync(string sessionKey, int parentMailIntKey, string parentMailBox, string mailType, string composeMailAction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/SaveMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveMail(string sessionKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/SaveMail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SaveMailAsync(string sessionKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/SendMail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendMail(string sessionKey, int savedMailKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendMailAsync(string sessionKey, int savedMailKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/MarkAsReadOrUnread", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MarkAsReadOrUnread(string sessionKey, string mailKeyList, int readOrUnread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/MarkAsReadOrUnread", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MarkAsReadOrUnreadAsync(string sessionKey, string mailKeyList, int readOrUnread);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/SendReadReceipt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendReadReceipt(string sessionKey, string mailKeyList, int sendResponseAsRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/SendReadReceipt", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendReadReceiptAsync(string sessionKey, string mailKeyList, int sendResponseAsRead);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetMailThread", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMailThread(string sessionKey, int mailIntKey, string mailBox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetMailThread", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetMailThreadAsync(string sessionKey, int mailIntKey, string mailBox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListMailForAllProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListMailForAllProjects(string sessionKey, string mailBox, string mailFilter, string mailAccessLevel, string orderBy, int startRowPosition, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListMailForAllProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListMailForAllProjectsAsync(string sessionKey, string mailBox, string mailFilter, string mailAccessLevel, string orderBy, int startRowPosition, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListMailForAllProjectsAsynchronous", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ListMailForAllProjectsAsynchronous(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/ListMailForAllProjectsAsynchronous", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ListMailForAllProjectsAsynchronousAsync(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetMailDetailsFromProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetMailDetailsFromProject(string sessionKey, string mailBox, int mailIntKey, int masterProjectKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetMailDetailsFromProject", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetMailDetailsFromProjectAsync(string sessionKey, string mailBox, int mailIntKey, int masterProjectKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetAttachmentsDownloadLinkFromProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAttachmentsDownloadLinkFromProject(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles, int masterProjectKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.qa-software.com/GetAttachmentsDownloadLinkFromProject", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAttachmentsDownloadLinkFromProjectAsync(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles, int masterProjectKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MailWebServiceSoapChannel : KiewitTeamBinder.Api.MailServiceReference.MailWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MailWebServiceSoapClient : System.ServiceModel.ClientBase<KiewitTeamBinder.Api.MailServiceReference.MailWebServiceSoap>, KiewitTeamBinder.Api.MailServiceReference.MailWebServiceSoap {
        
        public MailWebServiceSoapClient() {
        }
        
        public MailWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MailWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MailWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable ListMail(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows) {
            return base.Channel.ListMail(sessionKey, mailBox, mailFilter, mailAccessLevel, orderBy, startRowPosition, noOfRows);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListMailAsync(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows) {
            return base.Channel.ListMailAsync(sessionKey, mailBox, mailFilter, mailAccessLevel, orderBy, startRowPosition, noOfRows);
        }
        
        public System.Data.DataSet GetMailDetails(string sessionKey, string mailBox, int mailIntKey) {
            return base.Channel.GetMailDetails(sessionKey, mailBox, mailIntKey);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailDetailsAsync(string sessionKey, string mailBox, int mailIntKey) {
            return base.Channel.GetMailDetailsAsync(sessionKey, mailBox, mailIntKey);
        }
        
        public System.Data.DataSet GetAttachmentsDownloadLink(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles) {
            return base.Channel.GetAttachmentsDownloadLink(sessionKey, mailBox, mailKeyList, attachmentKeyList, zipSingleFiles);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAttachmentsDownloadLinkAsync(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles) {
            return base.Channel.GetAttachmentsDownloadLinkAsync(sessionKey, mailBox, mailKeyList, attachmentKeyList, zipSingleFiles);
        }
        
        public System.Data.DataTable ListNewMailTypes(string sessionKey) {
            return base.Channel.ListNewMailTypes(sessionKey);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListNewMailTypesAsync(string sessionKey) {
            return base.Channel.ListNewMailTypesAsync(sessionKey);
        }
        
        public System.Data.DataTable ListReplyForwardMailTypes(string sessionKey, string originatingMailType, string composeMailAction) {
            return base.Channel.ListReplyForwardMailTypes(sessionKey, originatingMailType, composeMailAction);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListReplyForwardMailTypesAsync(string sessionKey, string originatingMailType, string composeMailAction) {
            return base.Channel.ListReplyForwardMailTypesAsync(sessionKey, originatingMailType, composeMailAction);
        }
        
        public System.Data.DataSet GetStructureForComposeMail(string sessionKey, int parentMailIntKey, string parentMailBox, string mailType, string composeMailAction) {
            return base.Channel.GetStructureForComposeMail(sessionKey, parentMailIntKey, parentMailBox, mailType, composeMailAction);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetStructureForComposeMailAsync(string sessionKey, int parentMailIntKey, string parentMailBox, string mailType, string composeMailAction) {
            return base.Channel.GetStructureForComposeMailAsync(sessionKey, parentMailIntKey, parentMailBox, mailType, composeMailAction);
        }
        
        public string SaveMail(string sessionKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox) {
            return base.Channel.SaveMail(sessionKey, mailType, mailDetailsXml, composeMailAction, parentMailIntKey, parentMailBox);
        }
        
        public System.Threading.Tasks.Task<string> SaveMailAsync(string sessionKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox) {
            return base.Channel.SaveMailAsync(sessionKey, mailType, mailDetailsXml, composeMailAction, parentMailIntKey, parentMailBox);
        }
        
        public string SendMail(string sessionKey, int savedMailKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox) {
            return base.Channel.SendMail(sessionKey, savedMailKey, mailType, mailDetailsXml, composeMailAction, parentMailIntKey, parentMailBox);
        }
        
        public System.Threading.Tasks.Task<string> SendMailAsync(string sessionKey, int savedMailKey, string mailType, string mailDetailsXml, string composeMailAction, int parentMailIntKey, string parentMailBox) {
            return base.Channel.SendMailAsync(sessionKey, savedMailKey, mailType, mailDetailsXml, composeMailAction, parentMailIntKey, parentMailBox);
        }
        
        public string MarkAsReadOrUnread(string sessionKey, string mailKeyList, int readOrUnread) {
            return base.Channel.MarkAsReadOrUnread(sessionKey, mailKeyList, readOrUnread);
        }
        
        public System.Threading.Tasks.Task<string> MarkAsReadOrUnreadAsync(string sessionKey, string mailKeyList, int readOrUnread) {
            return base.Channel.MarkAsReadOrUnreadAsync(sessionKey, mailKeyList, readOrUnread);
        }
        
        public string SendReadReceipt(string sessionKey, string mailKeyList, int sendResponseAsRead) {
            return base.Channel.SendReadReceipt(sessionKey, mailKeyList, sendResponseAsRead);
        }
        
        public System.Threading.Tasks.Task<string> SendReadReceiptAsync(string sessionKey, string mailKeyList, int sendResponseAsRead) {
            return base.Channel.SendReadReceiptAsync(sessionKey, mailKeyList, sendResponseAsRead);
        }
        
        public System.Data.DataTable GetMailThread(string sessionKey, int mailIntKey, string mailBox) {
            return base.Channel.GetMailThread(sessionKey, mailIntKey, mailBox);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetMailThreadAsync(string sessionKey, int mailIntKey, string mailBox) {
            return base.Channel.GetMailThreadAsync(sessionKey, mailIntKey, mailBox);
        }
        
        public System.Data.DataTable ListMailForAllProjects(string sessionKey, string mailBox, string mailFilter, string mailAccessLevel, string orderBy, int startRowPosition, int noOfRows) {
            return base.Channel.ListMailForAllProjects(sessionKey, mailBox, mailFilter, mailAccessLevel, orderBy, startRowPosition, noOfRows);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListMailForAllProjectsAsync(string sessionKey, string mailBox, string mailFilter, string mailAccessLevel, string orderBy, int startRowPosition, int noOfRows) {
            return base.Channel.ListMailForAllProjectsAsync(sessionKey, mailBox, mailFilter, mailAccessLevel, orderBy, startRowPosition, noOfRows);
        }
        
        public string ListMailForAllProjectsAsynchronous(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows) {
            return base.Channel.ListMailForAllProjectsAsynchronous(sessionKey, mailBox, mailFilter, mailAccessLevel, orderBy, startRowPosition, noOfRows);
        }
        
        public System.Threading.Tasks.Task<string> ListMailForAllProjectsAsynchronousAsync(string sessionKey, string mailBox, string mailFilter, int mailAccessLevel, string orderBy, int startRowPosition, int noOfRows) {
            return base.Channel.ListMailForAllProjectsAsynchronousAsync(sessionKey, mailBox, mailFilter, mailAccessLevel, orderBy, startRowPosition, noOfRows);
        }
        
        public System.Data.DataSet GetMailDetailsFromProject(string sessionKey, string mailBox, int mailIntKey, int masterProjectKey) {
            return base.Channel.GetMailDetailsFromProject(sessionKey, mailBox, mailIntKey, masterProjectKey);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetMailDetailsFromProjectAsync(string sessionKey, string mailBox, int mailIntKey, int masterProjectKey) {
            return base.Channel.GetMailDetailsFromProjectAsync(sessionKey, mailBox, mailIntKey, masterProjectKey);
        }
        
        public System.Data.DataSet GetAttachmentsDownloadLinkFromProject(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles, int masterProjectKey) {
            return base.Channel.GetAttachmentsDownloadLinkFromProject(sessionKey, mailBox, mailKeyList, attachmentKeyList, zipSingleFiles, masterProjectKey);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAttachmentsDownloadLinkFromProjectAsync(string sessionKey, string mailBox, string mailKeyList, string attachmentKeyList, int zipSingleFiles, int masterProjectKey) {
            return base.Channel.GetAttachmentsDownloadLinkFromProjectAsync(sessionKey, mailBox, mailKeyList, attachmentKeyList, zipSingleFiles, masterProjectKey);
        }
    }
}
